### ISSUE TITLE
GPL-2.0 is a deprecated SPDX license

### ISSUE THREAD

**Issue by chenrui333** [GNS3/dynamips#249]
👋 GPL-2.0 is deprecated by [SPDX](https://spdx.org/licenses/GPL-2.0), please consider using [GPL-2.0-only](https://spdx.org/licenses/GPL-2.0-only) or [GPL-2.0-or-later](https://spdx.org/licenses/GPL-2.0-or-later). Thanks!

---

Need to update the license headers for the source files or just project readme to be more clear about the GPL license compatibility.

**Comment by flaviojs** [comment]
`This license identifier has been deprecated since license list version 3.0.`
I disagree with the deprecation, the existence of GPL-3.0 is not a good reason to deprecate GPL-2... they are **different** licenses.

This GPL-2.0-only and GPL-2.0-or-later alternatives are even weirder... the license text is the same, only the title and identifier in the page changed. A license is supposed to be legal text, right? If so then only the actual license text matters and both are bogus licenses?

Personally this whole license business is more of a burden to me. I would rather have my contributions to this project be public domain or similar (like Unlicense or CC0).

**Comment by grossmj** [comment]
We could consider showing [GPL-2.0-only](https://spdx.org/licenses/GPL-2.0-only) in the README.

FYI, GitHub only has GPLv2 or GPLv3:

![Screenshot from 2024-07-31 19-56-48](https://github.com/user-attachments/assets/9f3ae0b8-ce20-4c2b-9d7e-22614ee0f691)
