### ISSUE TITLE
Packet should not be dropped when the CAM table of router-based switches is full.

### ISSUE THREAD

**Issue by WhiteWinterWolf** [GNS3/dynamips#72]
I'm using a c3725 router device with a NM-16ESW module to use it as router-based switch, and use it to test and reproduce CAM table overflow attacks for security purposes.

The goal of this attack is to fill the switch's CAM table. To say it simply this forces the switch to flood packets through all its interfaces, allowing to eavesdrop communication which should not be reachable otherwise.

This attack is a well-known classic on real hardware, however it does not work in GNS3 because packets are being dropped as soon as the CAM table is full.

A more detailed analysis of the issue is available here: https://networkengineering.stackexchange.com/a/32567/27387

**Comment by whitewinterwolf** [comment]
This is due to a bug affecting the bcm5600_handle_rx_pkt() function in charge of handling received packets and located around line 2170 of the dev_nm_16esw.c file.

```
/* Source MAC address learning */
if (!bcm5600_src_mac_learning(d,p))
   return(FALSE);
```

Currently, when the ARL failed to store a new MAC address, the handling of the incoming is aborted, effectively resulting in the packet being drop. The fix is just to ignore the ARL status and continue processing the packet anyway, since this what real gear actually do:

```
/* Source MAC address learning */
bcm5600_src_mac_learning(d,p);
```

You will find the patch attached.
[dynamips-issue72.patch.txt](https://github.com/GNS3/dynamips/files/333655/dynamips-issue72.patch.txt)

**Comment by grossmj** [comment]
Thanks, I will apply the patch soon.
